### ISSUE TITLE
Getting error during Importing the maze model

### ISSUE THREAD

**Issue by mayank-srm** [googlecodelabs/arcore-augmentedimage-intro#6]
**java.lang.RuntimeException: java.lang.NoSuchMethodError: com.android.tools.idea.templates.recipe.RecipeExecutor.append(Ljava/io/File;Ljava/io/File;)V**

**Comment by aweck** [comment]
Same issue here.  I think it is connected to the sceneform SDK being updated and the old version not working with Android Studio 3.6.  

https://github.com/google-ar/sceneform-android-sdk/issues/989

**Comment by SuperBeagleDog** [comment]
I have this error too. Anyone knows there is a way can get around it?

**Comment by Junkuma** [comment]
I have same error.

java.lang.NoSuchMethodError: com.android.tools.idea.gradle.util.GradleUtil.getGradleBuildFilePath(Ljava/io/File;)Ljava/io/File;

**Comment by kai-dream** [comment]
Hi,

Thanks for reporting this issue, and thanks for trying out this codelab!

Given Sceneform SDK is no longer part of ARCore's release package, I updated this codelab to be based on ARCore Android SDK augmented_image_java sample, removing the dependency of Sceneform. 

Regards
Kai
